I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 148, in script
    allen "Yes, Detective."
Exception: Sayer 'allen' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 148, in script
    allen "Yes, Detective."
  File "/Applications/renpy-8.3.7-sdk/renpy/ast.py", line 2586, in execute
    Say.execute(self)
  File "/Applications/renpy-8.3.7-sdk/renpy/ast.py", line 583, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Applications/renpy-8.3.7-sdk/renpy/ast.py", line 472, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'allen' is not defined.

macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.3.7.25031702
Psych 1.0
Thu Apr  3 13:12:00 2025
